POST http://localhost:3000/employee/
Content-Type: application/json

{
    "ename":"hem",
    "eemail":"hem`@gmail.com"
}

###
GET http://localhost:3000/employee/

###

GET http://localhost:3000/employee/1

###
DELETE http://localhost:3000/employee/hem

###

POST http://localhost:3000/employee/update/3

Content-Type: application/json
{
    "ename":"margin",
    "eemail":"margin@gmail.com"
}

###
POST http://localhost:3000/emp/createemployee


###
GET http://localhost:3000/empapi

###
GET http://localhost:3000/empapi/coronadata

###
GET http://localhost:3000/empapi/postemp

###
GET http://localhost:3000/empapi/postuser
###

POST  http://localhost:3000/empapi/post

Content-Type: application/json
{
    "gender":"Male",
    "status":"Active",
    "email":"hem@gmail.com"
}

###
GET http://localhost:3000/empapi/deleteusern

